services:
  db:
    image: docker.io/postgres:18.3
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tx_relay
    ports: ["5432:5432"]
    volumes: ["postgres_data:/var/lib/postgresql"]
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.8.1
    restart: always
    entrypoint: ["anvil"]
    command: ["--host", "0.0.0.0"]
    ports: ["8545:8545"]
volumes:
  postgres_data:
